#  Need to update this at the start of every season
#  This file is to map names of players and teams between the official fpl api and the understat api

teams= [
    'Arsenal',
    'Aston Villa',
    'Brighton',
    'Burnley',
    'Sheffield United',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Fulham',
    'Leeds',
    'Leicester',
    'Liverpool',
    'Manchester City',
    'Manchester United',
    'Newcastle United',
    'Southampton',
    'Tottenham',
    'West Brom',
    'West Ham',
    'Wolverhampton Wanderers'
]


# from get_understat_data df_matches
team_ids = {
    86: 'Newcastle United',
    83: 'Arsenal',
    87: 'Liverpool',
    90: 'Watford',
    89: 'Manchester United',
    238: 'Sheffield United',
    75: 'Leicester',
    79: 'Norwich',
    81: 'West Ham',
    72: 'Everton',
    73: 'Bournemouth',
    78: 'Crystal Palace',
    80: 'Chelsea',
    92: 'Burnley',
    88: 'Manchester City',
    220: 'Brighton',
    74: 'Southampton',
    229: 'Wolverhampton Wanderers',
    82: 'Tottenham',
    71: 'Aston Villa'
}

#
# teams_trans = {
#     1: 'Arsenal',
#     2: 'Bournemouth',
#     3: 'Brighton',
#     4: 'Burnley',
#     5: 'Cardiff',
#     6: 'Chelsea',
#     7: 'Crystal Palace',
#     8: 'Everton',
#     9: 'Fulham',
#     10: 'Huddersfield',
#     11: 'Leicester',
#     12: 'Liverpool',
#     13: 'Man City',
#     14: 'Man U',
#     15: 'Newcastle',
#     16: 'Southampton',
#     17: 'Spurs',
#     18: 'Watford',
#     19: 'West Ham',
#     20: 'Wolves'
# }

position_trans = {
    1: 'GK',
    2: 'Defender',
    3: 'Midfielder',
    4: 'Striker'
}

player_trans = {
    'José Ángel Esmorís Tasende': 'Angelino',
    'José Diogo Dalot Teixeira': 'Diogo Dalot',
    'Djibril Sidibé': 'Djibril Sidibe',
    'Frédéric Guilbert': 'Frederic Guilbert',
    'Ismaïla Sarr': 'Ismaila Sarr',
    "Jack O'Connell": 'Jack O&#039;Connell',
    'Jesús Vallejo Lázaro': 'Jesús Vallejo',
    'João Pedro Cavaco Cancelo': 'João Cancelo',
    'Roberto Jimenez Gago': 'Roberto Jiménez',
    'Muhamed Bešić': 'Muhamed Besic',
    'Mahmoud Ahmed Ibrahim Hassan': 'Trézéguet',
    'Ralf Fahrmann': 'Ralf Fährmann',
    'Pedro Rodríguez Ledesma': 'Pedro',
    'Willian Borges Da Silva': 'Willian',
    "N'Golo Kanté": 'N&#039;Golo Kanté',
    'Jorge Luiz Frello Filho': 'Jorginho',
    'Richarlison de Andrade': 'Richarlison',
    'Frederico Rodrigues de Paula Santos': 'Fred',
    'Gabriel Fernando de Jesus': 'Gabriel Jesus',
    'Fernando Luiz Roza': 'Fernandinho',
    'Robert Kenedy Nunes do Nascimento': 'Kenedy',
    'David Luiz Moreira Marinho': 'David Luiz',
    'Sokratis Papastathopoulos': 'Sokratis',
    'Jose Luis Mato Sanmartín': 'Joselu',
    'Alisson Ramses Becker': 'Alisson',
    'Ederson Santana de Moraes': 'Ederson',
    'David De Gea': 'David de Gea',
    'Rui Pedro dos Santos Patrício': 'Rui Patrício',
    'Benjamin Chilwell': 'Ben Chilwell',
    'Solomon March': 'Solly March',
    'Isaac Success Ajayi': 'Isaac Success',
    'Rúben Diogo da Silva Neves': 'Rúben Neves',
    'Mathew Ryan': 'Mat Ryan',
    'João Filipe Iria Santos Moutinho': 'João Moutinho',
    'Jonathan Castro Otto': 'Jonny',
    'Bernardo Mota Veiga de Carvalho e Silva': 'Bernardo Silva',
    'Lucas Rodrigues Moura da Silva': 'Lucas Moura',
    'Felipe Anderson Pereira Gomes': 'Felipe Anderson',
    'Ricardo Domingos Barbosa Pereira': 'Ricardo Pereira',
    'Bamidele Alli': 'Dele Alli',
    'Kepa Arrizabalaga': 'Kepa',
    'Heung-Min Son': 'Son Heung-Min',
    'Mathias Jorgensen': 'Zanka',
    'Javier Hernández Balcázar': 'Chicharito',
    'Fernando Luiz Rosa': 'Fernandinho',
    'Sung-yueng Ki': 'Ki Sung-yueng',
    'Oriol Romeu Vidal': 'Oriol Romeu',
    'Fabricio Agosto Ramírez': 'Fabri',
    'Romain Saïss': 'Romain Saiss',
    'David Junior Hoilett': 'Junior Hoilett',
    'Ashley Darel Jazz Richards': 'Jazz Richards',
    'Francisco Femenía Far': 'Kiko Femenía',
    'Bernardo Fernandes da Silva Junior': 'Bernardo',
    'Bruno Saltor Grau': 'Bruno',
    'José Heriberto Izquierdo Mena': 'José Izquierdo',
    'André-Frank Zambo Anguissa': 'Franck Zambo',
    'Adrien Sebastian Perruchet Silva': 'Adrien Silva',
    'Greg Cunninghamm': 'Greg Cunningham',
    'Bonatini Lohner Maia Bonatini': 'Léo Bonatini',
    'Rúben Gonçalo Silva Nascimento Vinagre': 'Rúben Vinagre',
    'Bernard Anício Caldeira Duarte': 'Bernard',
    'Nicolas Pépé': 'Nicolas Pepe',
    'José Ignacio Peleteiro Romallo': 'Diogo Jota',
    'André Filipe Tavares Gomes': 'André Gomes',
    'Daniel Ceballos Fernández': 'Dani Ceballos',
    'Joseph Willock': 'Joe Willock',
    'Gabriel Teodoro Martinelli Silva': 'Gabriel Martinelli',
    'Ahmed El Mohamady': 'Ahmed Elmohamady',
    'Wesley Moraes': 'Wesley',
    'Bjorn Engels': 'Björn Engels',
    'Douglas Luiz Soares de Paulo': 'Douglas Luiz',
    'Emerson Palmieri dos Santos': 'Emerson',
    'Çaglar Söyüncü': 'Caglar Söyüncü',
    'Fabio Henrique Tavares': 'Fabinho',
    'Adrián San Miguel del Castillo': 'Adrián',
    'Rodrigo Hernandez': 'Rodri',
    'Joelinton Cássio Apolinário de Lira': 'Joelinton',
    'Maximillian Aarons': 'Max Aarons',
    'Tanguy Ndombele': 'Tanguy NDombele Alvaro',
    'Pedro Lomba Neto': 'Pedro Neto',
    'Bruno Miguel Borges Fernandes': 'Bruno Fernandes'

}


# 19/20
teams= [
    'Arsenal',
    'Aston Villa',
    'Bournemouth',
    'Brighton',
    'Burnley',
    'Sheffield United',
    'Chelsea',
    'Crystal Palace',
    'Everton',
    'Norwich',
    'Leicester',
    'Liverpool',
    'Manchester City',
    'Manchester United',
    'Newcastle United',
    'Southampton',
    'Tottenham',
    'Watford',
    'West Ham',
    'Wolverhampton Wanderers'
]
