teams_trans = {
    1: 'Arsenal',
    2: 'Bournemouth',
    3: 'Brighton',
    4: 'Burnley',
    5: 'Cardiff',
    6: 'Chelsea',
    7: 'Crystal Palace',
    8: 'Everton',
    9: 'Fulham',
    10: 'Huddersfield',
    11: 'Leicester',
    12: 'Liverpool',
    13: 'Man City',
    14: 'Man U',
    15: 'Newcastle',
    16: 'Southampton',
    17: 'Spurs',
    18: 'Watford',
    19: 'West Ham',
    20: 'Wolves'
}

position_trans = {
    1: 'GK',
    2: 'Defender',
    3: 'Midfielder',
    4: 'Striker'
}

player_trans = {
    'Pedro Rodríguez Ledesma': 'Pedro',
    'Willian Borges Da Silva': 'Willian',
    "N'Golo Kanté": 'N&#039;Golo Kanté',
    'Jorge Luiz Frello Filho': 'Jorginho',
    'Richarlison de Andrade': 'Richarlison',
    'Frederico Rodrigues de Paula Santos': 'Fred',
    'Gabriel Fernando de Jesus': 'Gabriel Jesus',
    'Fernando Luiz Roza': 'Fernandinho',
    'Robert Kenedy Nunes do Nascimento': 'Kenedy',
    'David Luiz Moreira Marinho': 'David Luiz',
    'Sokratis Papastathopoulos': 'Sokratis',
    'Jose Luis Mato Sanmartín': 'Joselu',
    'Alisson Ramses Becker': 'Alisson',
    'Ederson Santana de Moraes': 'Ederson',
    'David De Gea': 'David de Gea',
    'Rui Pedro dos Santos Patrício': 'Rui Patrício',
    'Benjamin Chilwell': 'Ben Chilwell',
    'Solomon March': 'Solly March',
    'Isaac Success Ajayi': 'Isaac Success',
    'Rúben Diogo da Silva Neves': 'Rúben Neves',
    'Mathew Ryan': 'Mat Ryan',
    'João Filipe Iria Santos Moutinho': 'João Moutinho',
    'Jonathan Castro Otto': 'Jonny',
    'Bernardo Mota Veiga de Carvalho e Silva': 'Bernardo Silva',
    'Lucas Rodrigues Moura da Silva': 'Lucas Moura',
    'Felipe Anderson Pereira Gomes': 'Felipe Anderson',
    'Ricardo Domingos Barbosa Pereira': 'Ricardo Pereira',
    'Bamidele Alli': 'Dele Alli',
    'Kepa Arrizabalaga': 'Kepa',
    'Heung-Min Son': 'Son Heung-Min',
    'Mathias Jorgensen': 'Zanka',
    'Javier Hernández Balcázar': 'Chicharito',
    'Fernando Luiz Rosa': 'Fernandinho',
    'Sung-yueng Ki': 'Ki Sung-yueng',
    'Oriol Romeu Vidal': 'Oriol Romeu',
    'Fabricio Agosto Ramírez': 'Fabri',
    'Romain Saïss': 'Romain Saiss',
    'David Junior Hoilett': 'Junior Hoilett',
    'Ashley Darel Jazz Richards': 'Jazz Richards',
    'Francisco Femenía Far': 'Kiko Femenía',
    'Bernardo Fernandes da Silva Junior': 'Bernardo',
    'Bruno Saltor Grau': 'Bruno',
    'José Heriberto Izquierdo Mena': 'José Izquierdo',
    'André-Frank Zambo Anguissa': 'Franck Zambo',
    'Adrien Sebastian Perruchet Silva': 'Adrien Silva',
    'Greg Cunninghamm': 'Greg Cunningham',
    'Bonatini Lohner Maia Bonatini': 'Léo Bonatini',
    'Rúben Gonçalo Silva Nascimento Vinagre': 'Rúben Vinagre',
    'Bernard Anício Caldeira Duarte': 'Bernard'

}
