# Here you can weight players based on their likeliness to get minutes

weights = {
    'David Silva': 0.8,
    'Ashley Young': 0.1,
    'James Milner': 0.7,
    'Paul Pogba': 1,
    'Sergio Agüero': 0.9,
    'Jamie Vardy': 1,
    'Davinson Sánchez': 1,
    'Joshua King': 1,
    'Ryan Fraser': 1,
    'Mat Ryan': 1.3,
    'Andrew Robertson': 1,
    'Paulo Gazzaniga': 1,
    'Willy Caballero': 1,
    'Fernandinho': 0.8,
    'Neco Williams': 0.8,
    "Reece James": 0.8,

    'Ederson': 0.8,
    'Christian Benteke': 0.8,
    'Olivier Giroud': 0.9,
    'Trent Alexander-Arnold': 1,
    'Leander Dendoncker': 1,
    'Nicolás Otamendi': 0.8,
    'Erik Lamela': 1,
    # 'Xherdan Shaqiri': 0.7,
    'Gabriel Jesus': 0.5,
    # 'Chicharito': 0.5,
    # 'Harvey Barnes': 0.5,
    'Dejan Lovren': 0.5,

    # 'Leroy Sané': 0.5,
    'Che Adams': 0.8,
    'Emerson': 0.8,
    'Kevin De Bruyne': 1,
    'Raheem Sterling': 0.9,
    'Bernardo Silva': 0.8,
    "Oleksandr Zinchenko": 0.1,
    'Adrián': 0.1,
    'Kurt Zouma': 0.7,
    'Christian Pulisic': 0.9,
    'Riyad Mahrez': 0.7,
    'Seamus Coleman': 1,
    'Marcos Alonso': 0.8,
    'Shane Long': 0.2,
    'Henrikh Mkhitaryan': 0.1,
    'João Cancelo': 0.8,
    'Chris Wood': 0.8,
    'Aymeric Laporte': 1,
    'Wes Morgan': 0.1,
    'Isaac Success': 0.1,
    'Kyle Walker': 0.7,
    'Luke Shaw': 1,
    'Eric Garcia': 0.1,
    'Phil Jones': 0.1,
    # 'Alex Iwobi': 0.9,
    'Harry Maguire': 1,
    'Diogo Dalot': 0.1,
    'Todd Cantwell': 1,
    'Xherdan Shaqiri': 0.1,
    'Ilkay Gündogan': 0.9,
    'Demarai Gray': 0.8,
    'Wesley': 1,
    'Mohamed Salah': 0.90,
    'Callum Hudson-Odoi': 0.8,
    'Andriy Yarmolenko': 1,
    'Bukayo Saka': 0.85,
    'Glenn Murray': 0.7,
    'John Lundstram': 0.9,
    'Bruno Fernandes': 1,
    'Matt Doherty': 0.8,
    'César Azpilicueta': 0.9,
    "Pierre-Emerick Aubameyang": 1.2,
    'Angelino': 0.1,
    'Tammy Abraham': 1,
    'John Stones': 0.7,
    'Ayoze Pérez': 0.8,
    'Willian': 0.9,
    'Claudio Bravo': 0.1,
    # 'Lys Mousset': 1.1,
    'Fikayo Tomori': 0.8,
    'Brandon Williams': 0.1,
    'Phil Foden': 0.8,
    'Ross Barkley': 0.9,
    'Harvey Barnes': 0.9,
    'Sadio Mané': 1,
    'Nick Pope': 1,
    'Christian Fuchs': 0.2,
    'Benjamin Mendy': 0.9,
    'Aaron Connolly': 0.5,
    'Rúben Vinagre': 0.1,
    'Son Heung-Min': 1,
    'Dele Alli': 0.9,
    'Max Kilman': 0.1

}